name: flutter_media_picker
description: A new Flutter package project.
version: 0.5.0
homepage: https://github.com/Iconica-Development/flutter_media_picker
publish_to: "none"

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.2
  image_picker: ^0.8.7
  file_picker: ^5.2.6
  video_player: ^2.6.0
  path_provider: ^2.0.13
  flutter_sound: ^9.2.13
  intl: ^0.17.0
  permission_handler: ^10.2.0
  logger: ^1.3.0
  flutter_form_wizard:
    git:
      url: https://github.com/Iconica-Development/flutter_form_wizard.git
      ref: 6.0.0
  mime: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
