name: flutter_media_picker
description: A new Flutter package project.
version: 0.6.5
homepage: https://github.com/Iconica-Development/flutter_media_picker

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.2
  image_picker: ^0.8.7
  file_picker: ^5.2.6
  video_player: ^2.6.0
  path_provider: ^2.0.13
  flutter_sound: ^9.2.13
  intl: ">=0.18.0 <1.0.0"
  permission_handler: ^10.2.0
  logger: ^1.3.0
  flutter_form_wizard:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^6.3.2
  mime: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
